name: Deploy to GitHub Pages

on:
  push:
    branches:
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: clone submodule
        uses: actions/checkout@v2
        with:
          repository: alex-ahr/vault
          path: content
          token: ${{ secrets.PERSONAL_KEY }}
          persist-credentials: true

      - name: checkout submodule
        run: |
          cd content
          git submodule init
          git submodule update --remote
          cd ..
      
      - name: Preprocess vault
        run: |
          chmod +x ./build.py
          ./build.py

      - name: Build Link Index
        uses: jackyzha0/hugo-obsidian@v2.18
        with:
          index: true
          input: content
          output: assets/indices
          root: .

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.96.0'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: master # deploying branch
          cname: alex-ahr.github.io/pkm
